### ISSUE TITLE
language support for the GNU Emacs editor

### ISSUE THREAD

**Issue by martinez** [nitlang/nit#1084]
Bonjour à tous.

I want to bring to your attention the availability of a new nit major mode for GNU Emacs.
The code is available for check out on my repository: https://github.com/martinez/nit-mode
Features so far include syntax coloring, comments and identation. As simple and rudimentary as it is now, I find it to work nicely with most source I have tried.

New to Nit programming as I am, I am sure this mode is far from complete. I invite the more advanced emacs+nit users (these people must exist, right?:) to use it and offer feedback.

A possibility for future improvement is source checking based on flycheck. Any other propositions for features are welcome.

**Comment by privat** [comment]
Excellent.

Est-ce que vous pouvez faire une PR qui intègre ces fichiers directement dans le répertoire `/misc/emacs` par exemple ? Ainsi, les utilisateurs auront plus facilement accès au mode emacs de Nit.

**Comment by privat** [comment]
@martinez do you plan to submit a PR ? If not, do you mind if I copy the files in a directory on the nit repository ? If you are fine with this, I can also point your repository as the main one.

**Comment by rgh36167** [comment]
Tested with Xemacs 21, it works but indentation could work better: hitting TAB in the line bellow a class def will indent the existing line to column 0. Does the same happen in GNU Emacs or is it an Xemacs specific problem?

Also the indentation keywords seem to miss "module", something like in '''`{''' and perhaps a few more.
