### ISSUE TITLE
No mission statement

### ISSUE THREAD

**Issue by jocull** [nitlang/nit#1107]
This is not a code issue, but something to consider for the website.

Nit looks like a very interesting language, but it has no mission statement. Why is it worth learning? Why should I consider it over Java, C#, Ruby... lang du jour?

There's a billion languages out there these days, and I thought it might be nice to have a few words about "Why Nit?". That's all! Thanks!

**Comment by privat** [comment]
Thank you for your suggestion (and sorry for the delay). A mission statement is definitely needed.
We will try to come up with something short and precise.

**Comment by privat** [comment]
new mission statement: Nit is an expressive language with a script-like syntax, a friendly type-system and aims at elegance, simplicity and intuitiveness.

Not perfect but it is something
