### ISSUE TITLE
Wild imports

### ISSUE THREAD

**Issue by xymus** [nitlang/nit#1265]
The frontend accepts importing submodules non-local to a group. It's better explained by this example accepted by the compiler:

~~~
import standard::egl::pipeline::android::mnit::mnit::mnit
~~~

Just to be clear, `standard` does not contain an `egl` module, nor does `egl` contain `pieline`... But you can access any module in the `lib/` directory as a submodule.

Is this normal? It can lead to importing an unexpected modules.

**Comment by privat** [comment]
It seems that the *look up in path* mode is used even if a parent is explicit. This part of the loader will need a rewrite any way when we will have a decision for #1250

**Comment by privat** [comment]
closed by #1667
