### ISSUE TITLE
Nit on windows

### ISSUE THREAD

**Issue by R4PaSs** [nitlang/nit#1338]
The compiler still does not work on Windows, it might be cool for the v1

**Comment by Morriar** [comment]
@BlackMinou good luck with that.

Also, the first step should be to add a Windows infra to Jenkins.

Again&copy;, good luck with that.

**Comment by privat** [comment]
doc: https://wiki.haskell.org/Windows

ping @xymus

**Comment by xymus** [comment]
I just installed Nit on Windows 10 using Cygwin. It is surprisingly easy but somewhat limited, here are my notes.

1. Install cygwin with the default packages and the following:

   `make ccache pkgconfig libisl10 libcloog-isl libgc-devel`

2. Then, from the cygwin command line, clone the Nit repo as usual:

   `git clone https://github.com/nitlang/nit.git`

   It will complain about the "very bad name" tests files. They cannot be represented on a Windows FS. Ignore this message, all other thousands of files should have unpacked successfully.

3. From the `nit` folder, run `make`, it will most likely not work on the first time. Here is how to fix each error:

   * If it complains about `\r` in `git-gen-version.sh`, run:

     `dos2unix src/git-gen-version.sh`

     and run `make` again.

   * If there is heap size errors, enlarge the heap of `nitc.exe` with:

     `peflags --cygwin-heap 4096 c_src/nitc.exe`

     and run `make` again.

     You may have to apply this command to all the bootstrap stages: `c_src/nitc.exe, src/nitc_0.exe, bin/nitc.exe`.

4. When you finally have a `bin/nitc.exe`, compile and execute hello_world with:

   ~~~
   bin/nitc.exe examples/hello_world.nit
   ./hello_world.exe
   ~~~

5. To distribute a program outside of the cygwin environment, copy the cygwin and libgc DDLs with the executable. More DLLs may be needed for programs using native libraries, but for `hello_world.exe` and `nitc.exe` only the following libraries are needed:

  `/bin/cyggc-1.dll /bin/cygwin1.dll`

6. More work is needed to actually develop Nit programs under a Windows environment. Simple programs like hello_world and Fibonacci work well outside of cygwin. However the compiler still expects UNIX-like paths and can't find nit_dir.

Additional notes:

* nitc reports all annotations as unknown, I'm not sure if they are applied but it hasn't caused any problems yet.
* I didn't find libunwind for cygwin, but I didn't search much either.
* Cygwin offers a somewhat limited set of libraries. So I haven't yet been able to compile game and nitcorn apps with this approach, but I haven't tried very hard. The missing libraries can probably be compiled from source.
* For a better and long term support of Windows for Nit, we should try using mingw/msys.

**Comment by xymus** [comment]
I kept looking into cygwin and managed to run gamnit games (OpenGL ES 2.0 with SDL 1.2). It's slow... but it works and it could be a starting point for other attempts.

1. Install additional cygwin libs:
   ~~~
   libGLESv2-devel libEGL-devel libSDL-devel libSDL-image-devel libSDL-ttf-devel xinit
   ~~~

2. Compile as usual with `make`, let's use Asteronits in `contrib/asteronits`.

3. Run in a X server with:
   ~~~
   xinit -e bin/asteronits.exe
   ~~~

**Comment by privat** [comment]
I tried the steps of @xymus ; its work.
So I copy-pasted to http://nitlanguage.org/windows.html (please review and improve it)

I also ran the tests manually (ie tests/, examples/ and lib/*/examples )

What worked: most of the things, including FFI, nitcorn, regexps, curl, threads and asteronits.

What did not work:

* opengles1 (so no mnit games)
* lib/socket/socket_c.nit (compilation error because missing FFI C symbols like AF_IPX)

**Comment by Nader-J** [comment]
libunwind-dev is'nt available yet?

**Comment by privat** [comment]
libunwind-dev is not mandoatory. (the message seems a bit scary and misleading)
