### ISSUE TITLE
Unable to clone the repo on window 8.1

### ISSUE THREAD

**Issue by ventilooo** [nitlang/nit#1356]
$ git clone http://nitlanguage.org/nit.git
Clonage dans 'nit'...
remote: Counting objects: 55392, done.
remote: Compressing objects: 100% (15242/15242), done.
remote: Total 55392 (delta 39467), reused 54490 (delta 38729)
Réception d'objets: 100% (55392/55392), 43.99 MiB | 604.00 KiB/s, fait.
Résolution des deltas: 100% (39467/39467), fait.
Vérification de la connectivité... fait.
error: unable to create file tests/--base_very bad name@1&$|;:.ext'"<>{}`~!#^*()_=+[]\,?.nit (No such file or directory)
error: unable to create file tests/sav/--base_very bad name@1&$|;:.ext'"<>{}`~!#^*()_=+[]\,?.res (No such file or directory)
Extraction des fichiers: 100% (4962/4962), fait.
fatal: impossible d'extraire la copie de travail
warning: Le clone a réussi, mais l'extraction a échoué.
Vous pouvez inspecter ce qui a été extrait avec 'git status'
et réessayer l'extraction avec 'git checkout -f HEAD'

**Comment by R4PaSs** [comment]
Hmmm, this is brutally phrased, but the issue is probably due to the names, NTFS probably prohibits some of the characters in the name of the tests here, namely `/ ? < > \ : * | "`, which are allowed on Linux.

As this is linked to #1338, @BlackMinou should take a look at this.

**Comment by privat** [comment]
This file is here to ensure that files with crazy names does not cause the tools to fail. But we did not thought about file systems that cannot handle such a name.

I would be tempted to suggest that you upsteam the bug to git since it seems there is no fallback to handle bad ntfs names; for instance, symbolic links have a fallback that makes them invalid but does not cause the whole clone process to fail.

**Comment by xymus** [comment]
In the long term, if this test cannot be tested on Windows it will be a problem. We should probably remove a bit of crazyness from the crazy name test.

**Comment by privat** [comment]
Can someone who has an easy access to a win+ntfs partition rename the file so that cloning work?
I tried on a debian+fat file system (usb stick) and the clone was successful, I am out of resources now.

**Comment by ventilooo** [comment]
ping ? @BlackMinou

**Comment by privat** [comment]
The issue is more an inconvenience than anything else. As the issue and a workaround is documented in http://nitlanguage.org/windows.html, I close.
