### ISSUE TITLE
Property pages can degenerate

### ISSUE THREAD

**Issue by privat** [nitlang/nit#1563]
The most redefined property is the virtual type SELF since it is redefined in each class.

Therefore, the doc page of SELF, if we include lib+src with private, is over 9000kB.

http://nitlanguage.org/doc/stdlib/property_core__kernel__Object__SELF.html

**Comment by jcbrinfo** [comment]
Also, `SELF` is documented in the page of every classes, which is unnecessary redundant.

**Comment by jcbrinfo** [comment]
The URL of the page mentioned by @privat is now <http://nitlanguage.org/doc/stdlib/property_core__kernel__Object__SELF.html>
