### ISSUE TITLE
Project metadata

### ISSUE THREAD

**Issue by privat** [nitlang/nit#1655]
As a follow-up of #1250 and #1654, a specification of key-value for the project metadata is expected.

The current proposition is at http://nitlanguage.org/nep/package_metadata.html
This issue is for discussion and comments

**Comment by privat** [comment]
I added a key `project.maintainer` to qualify the current manager(s) of the project. The `project.author` is still here but I'm not sure what is the right definition (main authors? original authors? all contributors? need to repeat the maintainers?).
I think that the full contributor list should be available trough the repository (`git short-log`).

**Comment by R4PaSs** [comment]
I'm not sure `project.author` (regardless of what it means) is an information that should be maintained, as you mentioned, it can be fetched from the versioning system, as such, it has no real purpose in the project metadata.

**Comment by privat** [comment]
I can ditch author completely and keep only maintainer.

**Comment by privat** [comment]
proposal: keep only a field `maintainer` with a list of maintainer (usually one person); add an optional field `project.more_contributors` to mention people not present in the git history (for some reason).

**Comment by R4PaSs** [comment]
Sounds good to me !

**Comment by privat** [comment]
new question: default source directory `src` or `.`?

**Comment by privat** [comment]
Regarding the last question, most (if not all) projects in lib/ do not have a src directory.

**Comment by privat** [comment]
I ask myself if the section `[projects]`, `[source]` and `[upstream]` are that useful. maybe core keys can be sectionless but extensions can be in section to protect them.
