### ISSUE TITLE
Rename `Map::recover_with`

### ISSUE THREAD

**Issue by Morriar** [nitlang/nit#1767]
This name is a joke, nobody understand what it does wihout looking at the doc...

What about `merge` instead?

**Comment by R4PaSs** [comment]
As it is an analoguous version of `SimpleCollection::add_all` as stated in documentation, why not rename it `add_all` then ?

If there are good reasons against the rename to `add_all`, I'd agree on `merge`

**Comment by Morriar** [comment]
@privat says: "not `add_all` because some items can be changed but not inserted."

**Comment by R4PaSs** [comment]
Good reason accepted. Let it be `merge` then !

**Comment by privat** [comment]
just do it
