### ISSUE TITLE
Unicode errors in Json static services

### ISSUE THREAD

**Issue by xymus** [nitlang/nit#1796]
Serializing a string to JSON may produce invalid characters.

I located the problem at the level of `json::static::Text::append_json` in the last `else` block. At that point, it correctly sees the unicode chars, but `buffer.add` may corrupt the char or buffer. You can see the corrupted output in `Text::to_json`.

Replacing the line `buffer.add char` with `buffer.append char.to_s` works... but @R4PaSs should be able to do better.

**Comment by R4PaSs** [comment]
Fixing `Buffer::add_char` should be more than enough :)

Any chance you have a dumbed-down bug example to ease the search ?
