### ISSUE TITLE
Add a logging module for nitcorn

### ISSUE THREAD

**Issue by xymus** [nitlang/nit#1802]
Goal: Using class refinement, add a logging system to nitcorn to ease the debugging of Web apps and help to detect abuse.

This system should rely on the existing `print` and `print_error`. Expect stdout and stderr to be handled by an outside services which takes care of writing the messages to a log file.

- [x] Use the standard nitcorn entry points like `Action::answer` to mark the beginning and end of actions, and associate the following messages to a precise action.
- [x] Add timestamps to `print` and `print_error` by refinement.
- [x] Count the execution time of each answer to a request using a `Clock` and storing the results in a `sys.perfs` from `performance_analysis`. Print a summary every `some_customizable_variable` requests.

**Comment by privat** [comment]
closed by #1869
