### ISSUE TITLE
Write a nitcorn example implementing HTCPCP

### ISSUE THREAD

**Issue by xymus** [nitlang/nit#1808]
Goal: Implement the Hyper Text Coffee Pot Control Protocol as a sample nitcorn program. You can assume that the server runs on a Raspberry Pi and sends signals to a coffeemaker through relays or pins (then use the `bcm2835` module). Or, assume that it simply displays the orders on the console to a barista.

Ref: https://tools.ietf.org/html/rfc2324

**Comment by itsWill** [comment]
@Bl4ckb0ne, @xymus, is anyone working on this issue or has this issue been completed?

**Comment by R4PaSs** [comment]
@Bl4ckb0ne had started working on it if I recall correctly for the last coding party, though I'm not sure he completed the work and it has not been PR'd, so I can confidently say that you're welcome to start working on it if you feel like it :)

**Comment by Bl4ckb0ne** [comment]
After a while, I figured out that the HCPCP protocol can't really be implemented in the nitcorn library. The user have to do it itself, because it depends on many things (principally the coffe pot). However, if you want to do it, or mess around, go for it.

**Comment by privat** [comment]
closed by #1915
