### ISSUE TITLE
nitcorn application for nitiwiki

### ISSUE THREAD

**Issue by xymus** [nitlang/nit#1832]
nitiwiki is a simple wiki manager based on markdown files and git repositories. Nitiwiki generates a static site from the markdown source and does not yet offer any dynamic features. For more information, see http://nitlanguage.org/catalog/p/nitiwiki.html

Goal: Write a nitcorn application to add and edit content of a nitwiki server from the browser.

- [x] This application should display a simple form, accepts POST submissions, write the content to markdown files, and trigger nitiwiki to regenerate the static content.
- [x] Add an option to display a preview using the `markdown` module.
- [x] Integrate this interface with the default template of Nitiwiki. 
- [x] Document how to install this application alongside an existing nitiwiki structure.
- [x] Implement a minimal access control using a simple server side structure, such as a `Map[String, String]` filled from a text file.

**Comment by ablondin** [comment]
I've started something which can be found in commit a06994a27c20fba3b378a33a373f170952acb866. I don't know when I'll have time to continue. Don't hesitate to start from it if you're interested...

**Comment by privat** [comment]
@ablondin please PR the current code, reviewer will help to improve it so it could be merged
