### ISSUE TITLE
Unicode support broken on iOS

### ISSUE THREAD

**Issue by xymus** [nitlang/nit#1945]
Unicode support is broken on iOS. The effect is visible in the Tnitter app #1943 where Unicode text outside the ASCII range is scrambled.

The problem appears to originate in `char_at`, it is detected by clang which prints the following warnings:

```
/Users/xymus/projects/nit/contrib/tnitter/nit_compile/ios/tnitter_app_m/core__native.sep.1.c:670:15: warning:
      comparison of constant 3221225472 with expression of type 'long' is always false
      [-Wtautological-constant-out-of-range-compare]
var31 = var26 == 3221225472l;
        ~~~~~ ^  ~~~~~~~~~~~
/Users/xymus/projects/nit/contrib/tnitter/nit_compile/ios/tnitter_app_m/core__native.sep.1.c:779:15: warning:
      comparison of constant 3758096384 with expression of type 'long' is always false
      [-Wtautological-constant-out-of-range-compare]
var68 = var63 == 3758096384l;
        ~~~~~ ^  ~~~~~~~~~~~
/Users/xymus/projects/nit/contrib/tnitter/nit_compile/ios/tnitter_app_m/core__native.sep.1.c:913:17: warning:
      comparison of constant 4026531840 with expression of type 'long' is always false
      [-Wtautological-constant-out-of-range-compare]
var114 = var109 == 4026531840l;
         ~~~~~~ ^  ~~~~~~~~~~~
3 warnings generated.
```

Note that the same code works on 32 bits Android, where the Tnitter app correctly displays Unicode text.

**Comment by privat** [comment]
maybe `uint32_t` should be used to avoid bad surprises (and `UINT32_C(3221225472)` for the literal)

**Comment by xymus** [comment]
This issue should not have been (automatically) closed. #2021 only fixed a visible bug, not the underlying problem, the compilation errors are still present, unicode text is not cleaned and there are still visible bugs on physical devices. However, I'll have a temporary workaround soon.
