### ISSUE TITLE
nit interpreter let some compile dir in the directory

### ISSUE THREAD

**Issue by privat** [nitlang/nit#1974]
Some `nit_compile` directory is not cleaned

~~
$ du -sh nit_compile
du: cannot access 'nit_compile': No such file or directory
$ nit examples/hello_world.nit
hello world
$ du -sh nit_compile
380K	nit_compile
~~~

**Comment by xymus** [comment]
It contains the generated native libraries for the FFI (.so) and their source files. We can certainly delete the source files. But what to do of the libraries? delete them also or keep them for reuse?

**Comment by privat** [comment]
I see two solutions: put them in (or near) the directory of the nit module (à la Python.) or put them in the home (in the cache subdit for instance, à la cccache)
