### ISSUE TITLE
nit interpreter cannot interpret its own ffi

### ISSUE THREAD

**Issue by privat** [nitlang/nit#2018]
The following program cannot by run by the interpreter on the interpreter

~~~nit
import core::kernel

fun foo `{ printf("FOO\n"); `}
fun bar(i: Int) `{ printf("BAR %ld\n", i); `}
fun baz: Int `{ printf("BAZ\n"); return 42; `}

foo
bar(1)
bar(baz+1)
~~~

~~~
$ nit base_ffi.nit 
FOO
BAR 1
BAZ
BAR 43

$ nit src/nit.nit base_ffi.nit
src/interpreter/dynamic_loading_ffi/dynamic_loading_ffi.nit:130,2--131,66: Runtime error: NOT YET IMPLEMENTED extern dynamic_loading_ffi#CallArg#instance=
~~~

This makes sense because the `instance=` method takes a non-primitive parameter that is not handled by the niti ffi.
However, this is not nice since the interpreter cannot interpret itself on the simple hello-word program.

A possible solution could be to pass non-primitive objects as opaque (void*).

Reported-by: @BlackMinou

**Comment by xymus** [comment]
It's the heuristic that identifies the method as full FFI, and thus rejects it. I could fix this with an annotation declaring it as light FFI.
