### ISSUE TITLE
Contribution guidelines are hard to find

### ISSUE THREAD

**Issue by tonygaetani** [nitlang/nit#2133]
Before I submitted a pull request I was looking for some contribution guidelines but I couldn't find any. Well, they do exist, I just couldn't find them. Maybe add a link in README or something?

http://nitlanguage.org/internal/patches.html

Just a thought.

**Comment by jcbrinfo** [comment]
Current path: All documentation… -> Get Involved -> Patches

**Comment by R4PaSs** [comment]
I do agree on this, most open-source projects do have a contributing section within their introduction README, Nit would certainly benefit from one !

We should also provide a `CONTRIBUTING.md` file along with it, this can only help people wanting to contribute in a way or another, by redirecting them to newcomer-related issues and the like.

Thanks for the suggestion !
