### ISSUE TITLE
nitweb: style and nitpick

### ISSUE THREAD

**Issue by privat** [nitlang/nit#2177]
- [x] less drop shadow
- [x] add some feedback to distinguish nothing v.s. still working. E.g. either add a spin when searching, or display a `nothing found` message if the search is empty
- [ ] sync location and tabs. so bookmarks, history and sharing links works as expected

**Comment by jcbrinfo** [comment]
- [ ] Set the font family in GraphViz to generate more readable graphs (i.e. do not display `popcorn` as `popcom`).

**Comment by jcbrinfo** [comment]
- [ ] Make of links on source locations do something useful or make them regular text.

**Comment by jcbrinfo** [comment]
- [ ] Do not `overflow: hidden` as it crops the page on small screens.

**Comment by jcbrinfo** [comment]
- [ ] Order properties of a class by names.

**Comment by jcbrinfo** [comment]
- [ ] Do not use hovering as a mean to hide stuff because users can not hover with a touch screen and because there is no visual clue that indicates where to find the hidden stuff.
