### ISSUE TITLE
Adaptative typing bug

### ISSUE THREAD

**Issue by xymus** [nitlang/nit#2202]
The type check (and if block) in the following programs seems to confuse the adaptative typing on the var `x`. The last statement throws an error because the static type has been changed to `A`.

~~~
class A
end

class B
	super A

	fun bar do print "bar"
end

var x = new B
if x isa A then print "x isa A" # Comment out and it works
x.bar # Error: method `bar` does not exists in `A`.
~~~

**Comment by privat** [comment]
good catch. I will investigate
