### ISSUE TITLE
nitiwiki_server build error 

### ISSUE THREAD

**Issue by egagnon** [nitlang/nit#2324]
$ make
mkdir -p bin
nitc src/nitiwiki.nit -o bin/nitiwiki
nitc -o bin/nitiwiki_server src/wiki_edit.nit
/[...]/nit/lib/libevent.nit:22,20--40: Error: package `libevent` unknown by `pkg-config`, make sure the development package is be installed.
	module libevent is pkgconfig("libevent")
	                   ^
Errors: 1. Warnings: 0.
Makefile:8 : la recette pour la cible « bin/nitiwiki_server » a échouée
make: *** [bin/nitiwiki_server] Erreur 1

**Comment by jpcaissy** [comment]
> Error: package libevent unknown by pkg-config, make sure the development package is be installed.


On debian-like, `apt-get install libevent-dev` should fix the issue.

**Comment by egagnon** [comment]
It worked.
This should probably be documented somewhere, like in a ReadMe. ;)
