### ISSUE TITLE
Dropbox-api - which http interface?

### ISSUE THREAD

**Issue by rgh36167** [nitlang/nit#2588]
Trying the dropbox-api - it seems that the lib/curl interface on Linux would be fine for this but neither the lib/app/http_request nor  lib/android/http_request  have equivalent capabilities. Are there other http libs which I have missed?

**Comment by privat** [comment]
The curl library is used for rest client. https://github.com/nitlang/nit/tree/master/lib/curl/

`git grep 'import curl'` gives you some clients that you might look at.

**Comment by rgh36167** [comment]
did anyone use libcurl on Android? I am uncertain whether I should do this or try to get the equivalent functionality from the native Java libraries.
