### ISSUE TITLE
Regression: error compiling the system

### ISSUE THREAD

**Issue by rgh36167** [nitlang/nit#2619]
Did a git pull on 2.3.2018 and suddenly make fails:

```
$ make
cd src; make
make[1]: Entering directory '/home/rz/linux-prog/nit-lang/nit/src'
***************************************************************
* Compile binaries from NIT source files                      *
***************************************************************
./git-gen-version.sh
test -d ../bin || mkdir ../bin
./nitc_0 --semi-global -v --dir ../bin nitc.nit nitpick.nit nit.nit nitdoc.nit nitls.nit nitunit.nit picnit.nit nitpretty.nit nitmetrics.nit nitx.nit nitlight.nit nitserial.nit nitrestful.nit
*** PARSE ***
*** SEMANTIC ANALYSIS ***
../lib/curl/curl.nit:296,6--32: Error: untyped attribute `curl$CurlMail$supported_outgoing_protocol`. Implicit typing allowed only for literals and new.
                var supported_outgoing_protocol = ["smtp", "smtps"]
                    ^
Errors: 1. Warnings: 0.
Makefile:42: recipe for target 'bin/nitc' failed
make[1]: *** [bin/nitc] Error 1
make[1]: Leaving directory '/home/rz/linux-prog/nit-lang/nit/src'
Makefile:43: recipe for target 'tools' failed
make: *** [tools] Error 2
```

**Comment by rgh36167** [comment]
The obvious fix in curl.nit gets me further, after a warning
```
./doc/commands/commands_base.nit:54,16--25: Error: a class named `nitc::DocCommand` is already defined in module `doc_commands` at ./doc/doc_commands.nit:182,1--205,3. (full-name-conflict)
        abstract class DocCommand
                       ^
```
and the final error - out of memory:
```
*** PROCESS nitdoc ***
*** GENERATING C ***
GC Warning: Failed to expand heap by 16777216 bytes
```

this is a 32 bit system but it did not happen a few weeks ago.

**Comment by rgh36167** [comment]
watching the compilation with top, the memory usage remains very stable around 1.2GB for a long while and suddenly jumps to over 3G in an instant. So pretty sure it is a new problem in the compiler somewhere.. should have opened a new issue for that?

Unfortunately no stack trace..

**Comment by xymus** [comment]
The first issue is caused by a `src/nitc_0` that is not recompiled properly. You can remove `src/nitc_0`, or even better, force a full bootstrap with `rm c_src/nitc`, before running `make` again.

I also get the error on DocCommand but it compiles anyway. Could it be that this message appears so often when compiling nitdoc that the memory explodes? What do you think @privat?

You could try to remove `nitdoc` from the `OBJS=` line at the top of `src/Makefile` as a workaround and to see if it crashes on the next tool.

**Comment by privat** [comment]
As @xymus says, the nitc_0 was too old. Maybe we should force the regeneration of nitc_0 on an explicit make.

The DocCommand error is not a real error, more a warning. the whole nit{doc,x,web} toolsuite is in a major refactorisation so there is some nasty name clashes.

For the memory consumption, I just checked on a fresh install. nitc requires a maximum of 1.3GB on my 64 bits system. gcc and other tools require approximately 500MB more. I'm not sure why you did see a 3GB spike.
Note that maybe on a 32 bits system the consumption can be different as the garbage collector might behave differently.

nitdoc is a big tool and maybe we could make it optional as it is available on the website.

**Comment by rgh36167** [comment]
> As @xymus says, the nitc_0 was too old. Maybe we should force the regeneration of nitc_0 on an explicit make.

compared to compiling the rest of the system this does not seem to cause noticeable delays? Or maybe there could be an extra build or clean target in the Makefile.

After fixing the issue caused by nitc_0 the problem with nitdoc is gone, it spits out 4 messages like ```GC Warning: Failed to expand heap by 16777216 bytes``` but compiles fairly quickly.

Worse is nitunit which gave a few scary messages like 
```
GC Warning: Out of memory - trying to allocate less
GC Warning: Header allocation failed: Dropping block.
GC Warning: Out of memory - trying to allocate less
GC Warning: Header allocation failed: Dropping block.
```
and took rather long. 

Compiling nitmetrics crashes with OOM fairly quickly.

```
*** PROCESS nitmetrics ***
*** GENERATING C ***
GC Warning: Out of memory - trying to allocate less
GC Warning: Header allocation failed: Dropping block.
GC Warning: Out of memory - trying to allocate less
GC Warning: Header allocation failed: Dropping block.
GC Warning: Out of memory - trying to allocate less
GC Warning: Header allocation failed: Dropping block.
GC Warning: Failed to expand heap by 16777216 bytes
GC Warning: Failed to expand heap by 262144 bytes
GC Warning: Out of Memory! Heap size: 2854 MiB. Returning NULL!
Caught signal : Segmentation fault
-------------------------------------------------
--   Stack Trace   ------------------------------
-------------------------------------------------
` 
` 
` 
```
