### ISSUE TITLE
Add UNIX socket support to libevent

### ISSUE THREAD

**Issue by matthmsl** [nitlang/nit#2679]
## Description
This issue is related to #2678 
Actually, libevent allow nitcorn to listen TCP sockets. I need to adapt this library to listen UNIX sockets. It seems I will have to work around  ```ConnectionFactory```, ```NativeEventBase``` and ```ConnectionListener```.

@xymus any suggestions on the best way to do it ? I thought about writing test on how the address input is written to determine if the lib will have to listen on a TCP or a UNIX socket. But it might be better to write another function to differentiate TCP from UNIX sockets creation/listening...

**Comment by xymus** [comment]
Yeah, adding methods for UNIX socket is probably the way to go, and it will limit the effects on the rest of the code.

You can extend `ConnectionListener` to add an alternative to the existing `new bind_to`. It looks like you can create a `sockaddr_un` instead of a `sockaddr_in` and it should just work.

You will also need an alternative to `ConnectionFactory::bind_to` for UNIX sockets, it acts as the public API entrypoint. Use it to convert from Nit types to C types and offer a clean API to nitcorn.

**Comment by matthmsl** [comment]
@xymus I have a few questions for you... It would help me better understanding what I'm doing and how to fix my code.
---
```nit
	# Create a new `Connection` object for `buffer_event`
	fun spawn_connection(buffer_event: NativeBufferEvent, address: String): Connection
	do
		return new Connection(buffer_event)
	end
```
Since this function doesn't use address, why is this parameter required ? Is there any hidden side effect ?

---
```nit
// Callback forwarded to 'ConnectionFactory.accept_connection'
	static void accept_connection_cb(struct evconnlistener *listener, evutil_socket_t fd,
		struct sockaddr *addrin, int socklen, ConnectionFactory ctx)
	{
		ConnectionFactory_accept_connection(ctx, listener, fd, addrin, socklen);
	}
```
...
```nit
fun accept_connection(listener: ConnectionListener, fd: Int, addrin: Pointer, socklen: Int)
	do
		var base = listener.base
		var bev = new NativeBufferEvent.socket(base, fd, bev_opt_close_on_free)

		# Human representation of remote client address
		var addr_len = 46 # Longest possible IPv6 address + null byte
		var addr_buf = new CString(addr_len)
		addr_buf = addrin_to_address(addrin, addr_buf, addr_len)
		var addr = if addr_buf.address_is_null then
				"Unknown address"
			else addr_buf.to_s

		var conn = spawn_connection(bev, addr)
		bev.enable ev_read|ev_write
		bev.setcb conn
	end
```
Could you clarify how it works ?
- How ```accept_connection_cb``` gets its parameters since they're not specified in ```evconnlistener_new_bind``` ?
- When does ```fun accept_connection``` is called ?
