### ISSUE TITLE
It's not possible to comment an annotation

### ISSUE THREAD

**Issue by Delja** [nitlang/nit#2786]
Currently annotation comment is not allowed. Example : 
```nit
class A
	fun bar 
	is 
		foo
		#baz
	do
	end
end
```
This code make an `Syntax Error: unexpected keyword 'do'.`

**Comment by Morriar** [comment]
```nit
class A
	fun bar
	is
		# foo comment
		foo
		# bar comment
		bar
	do
	end
end
```

**Comment by Morriar** [comment]
Feel free to reopen if I misunderstood your issue.

**Comment by R4PaSs** [comment]
I'd believe the aforementioned code should not provoke a syntax error as we have a single comment on a separate line, this definitely triggers my non POLA radar; the grammar should probably accept this
@privat what do you think?

**Comment by Delja** [comment]
@Morriar my problem, it's the grammar should be normally accept a "free" comment in an annotation block without causing a syntax error. The same as it's possible to put a comment without link it to a method.
example: 
```
class A


	# Some comments blabla
	# [....]


	fun bar
	do
	end
end
```
