### ISSUE TITLE
Legal license query

### ISSUE THREAD

**Issue by sincorchetes** [nitlang/nit#2834]
Hello somebody,

I'm just asking a legal query because I've installed this software and it may violate your software license. I've opened a post in Qt Community Forum to get more information from here: https://forum.qt.io/topic/154787/legal-support-query

Best wishes,

**Comment by privat** [comment]
Hi, I'm not sure how this is related to the nilanguage project.

**Comment by sincorchetes** [comment]
Sorry, but this project does not maintain GLES?

-a----        28/12/2023     14:16          42488 libEGL.dll
-a----        28/12/2023     14:16        2970104 libGLESv2.dll
