### ISSUE TITLE
Debugger is a pain to use

### ISSUE THREAD

**Issue by R4PaSs** [nitlang/nit#742]
In addition to the robustness issues mentioned in #703, a few modifications will need to be done on the use of the program itself :
- [x] Give short help on unknown or bad formatted command (see #703)
- [x] Do no crash on bad formatted command (see #703)
- [ ] For convenience, a bit more then file + line combo (stuff like `module::method` or just `method` could be nice, especially in Nit) must be supported by Breakpoints, it's getting boring to use.
- [x] Just get rid of the `.nit` suffix when declaring a breakpoint, it makes absolutely no sense, and it's error-prone !
- [x] FFS implement `bt` instead of `print stack` !
- [ ] Just implement `readline`, I'm tired of copy/pasting my commands !
- [ ] Improve the alias system, attach the Alias to an instance instead of a name
- [ ] Make the previous more robust by checking if a name already exists
- [ ] Just in case, make unit tests.
- [ ] Someday : a native debugger when debugging a big program could be nice too.

Rethorical/community question : When readline is implemented, aliases will be almost useless, should we keep it ?

**Comment by privat** [comment]
close because nit--debug was purged #2329.
maybe, a future dbg might be based on nitin #2409
